apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: densify
spec:
  containers:
  - name: wp
    image: wordpress
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"